# Generated by Django 4.2.4 on 2023-08-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_blogarticle_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='date_published',
            field=models.CharField(max_length=200),
        ),
    ]
