# Generated by Django 4.2.4 on 2023-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_blogarticle_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=models.TextField(),
        ),
    ]
